Update file_from_url.rb
Not defined variable, could be cause of problem during installation (tested on SLE-12-SP3), Information on screen expose detail described below
Details: Undefined local variable or method 'cdrom' from #<Yast:AutoinstScriptClass:0x00000004386ce8>
Caller: /usr/share/Yast2/lib/transfer/file_from_url.rb:271:in 'get_file_from_url'